---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

1. Inspect the first few lines of the dataset:

- what variables are there?
  ParcelID, Address, Style, Occupancy, Sale Date, Sale Price, Multi Sale, Year Built, Acres, Total Living Area (ft^2), Bedrooms, Finished Basement (ft^2), Lot Area (ft^2), AC, Fire place, Neighborhood
- of what type are the variables?
  chr, chr, factor with 12 levels, factor with 5 levels, date, num, chr, num, num, num, num, num, num, chr, chr, factor with 42 levels

-   what does each variable mean? The majority of these variables are fairly self explantory such as parcel ID, address, sale date, sale price, Year built, acres, total living area, bedrooms, finished basement, lot area, AC, and fireplace.

The variables that are unique include the style which details the type of housing with 12 different types listed. Occupancy which details the type of housing that this is. Multi sale which determines whether the house was sold as a package deal. And finally Neighborhood which indiciates which neighborhood this house is a part of.

- what do we expect their data range to be?

The data ranges for the variables are as follows:

Style: 1-12 which correlate with style factor

Occupancy: 1-5 which correlate with occupancy factor

Sale Date: Date between Jan 1 2017 and Decemeber 31 2022

Sale Price: Number between 0 and 20500000

Year Built: num between 0 and 2022

Acres: Number between 0 and 13

Total Living Area: Number between 0 and 6007

Bedrooms: Number between 0 and 10

Finished Basement Area: Number between 10 and 6496

Lot Area: Number between 0 and 523228

Neighborhood: 1-42 which correlates with Neighborhood factor

2. is there a variable of special interest or focus?
  The obvious variable of special interest is Sale Price; we chose this because all other variables have the potential to affect the Sale Price variable and it would likely have the highest range.

3. start the exploration with the main variable:

- what is the range of the variable? 
  The range is between 0-20500000
- draw a histogram for a numeric vaiable or a bar chart, if the variable is categorical. 
- what is the general pattern? is there anything odd?
- follow-up on oddities: see 4
  bring up multisale and many 0s

4. pick a variable that might be related to the main variable.

- what is the range of that variable? plot. describe the pattern.
- what is the relationship to the main variable? plot a scatterplot, boxplot or facetted barcharts (dependening on the types of variables involved). Describe overall pattern, does this variable describe any oddities discovered in 3? Identify/follow-up on any oddities.
